### ISSUE TITLE
CrazyGoblin dmg types

### ISSUE THREAD

**Issue by FelixReuthlinger** [VMP-Valheim/Monsters#3]
Can we plz reduce CrazyGoblin's Spirit to equal values as the other damage types?
Or maybe just remove spirit and poison? We can anyways scale him to be a hard hitter, no need to have all dmg types tbh - just makes it more difficult to calculate

**Comment by sbtoonz** [comment]
Sure do you have suggestions for good base val numbers for me to input that would yield easier calculations?

**Comment by FelixReuthlinger** [comment]
Maybe a combination of min/max 
pierce(blunt for ranged is kind of wrong ;) ) 50/70
fire 50/70
lightning 50/70 
?

For me it would also be ok, if only one of fire or lightning, since CLLC creature infusions already add some custom magic damage.
